### ISSUE TITLE
Searching POS in parameters doesn't search for all possible POS

### ISSUE THREAD

**Issue by thinkingbox12** [neocl/jamdict#25]
I noticed when using this solution for finding POS that we discussed in #22 :

```
# find all idseq of lexical entry (i.e. words) that have at least 1 sense with pos = suru verb - irregular
with jam.jmdict.ctx() as ctx:
    # query all word's idseqs
    rows = ctx.select(
        query="SELECT DISTINCT idseq FROM Sense WHERE ID IN (SELECT sid FROM pos WHERE text = ?)",
        params=("expressions (phrases, clauses, etc.)",))
    for row in rows:
        # reuse database connection with ctx=ctx for better performance
        word = jam.jmdict.get_entry(idseq=row['idseq'], ctx=ctx)
        ruler.add_patterns([{"label": "EXPRESSION", "pattern": x.text} for x in word.kanji_forms])
        ruler.add_patterns([{"label": "EXPRESSION", "pattern": x.text} for x in word.kana_forms])
        print("Working on expressions...")
```

that some expressions that have the 'expressions (phrases, clauses, etc.)' as a secondary parameter instead of primary seem to not be caught by this search. Is this a bug, or an intended feature?

Additionally, it seems that the original JMDict does not use this scheme to refer to expressions. Instead the term used is 'exp'. Am I mistaken here?

Thank you

**Comment by letuananh** [comment]
This is surprising. I think the query looks fine and it should detect all expressions. I can help to look into this. Do you have an example of the missing entries?

About `exp`, it is the name of an entity, as defined in the XML.

```
<!ENTITY exp "expressions (phrases, clauses, etc.)">
```

The text stored in the database is the expanded text. I actually should redesign this part of the database (shorter strings means smaller database too).
I haven't done so because it will break current jamdict installations (i.e. change of DB schema). It is still in my to do list and I'll proceed once I found a good solution, like supporting multiple database versions.

**Comment by thinkingbox12** [comment]
Thank you for taking a look at this. an example would be 大事にする... since expression is listed as the second POS instead of the first, I don't think it was recognized as an expression, but instead as an irregular suru verb

**Comment by letuananh** [comment]
Ah I see. In that case it is the issue of outdated database instead of a malfunction lookup. Once we fixed issue https://github.com/neocl/jamdict/issues/26 this problem will go away.

**Comment by thinkingbox12** [comment]
Fixed! Completely forgot that the phrase wasn't even in the dictionary to begin with. Thanks!!
